version: "2"
exclude_patterns:
  - "**/scripts/"
  - "**/*.d.ts"
  - "**/node_modules/"
  - "**/dist/"
  - "**/__test__/"
  - ".github/"
  - "screenshots/"
  - "packages/book-reader-test-plugin/"
  - "packages/graphql/generated/GQLTypes.ts"
  - "packages/server/src/sort/"
