FROM node:25.2.1-slim AS base

LABEL maintainer="syuchan1005<syuchan.dev@gmail.com>"
LABEL name="BookReader"

WORKDIR /bookReader

FROM base AS install
RUN mkdir -p /temp/dev
COPY package.json package-lock.json /temp/dev/
COPY packages/common/package.json /temp/dev/packages/common/
COPY packages/client/package.json /temp/dev/packages/client/
COPY packages/server/package.json /temp/dev/packages/server/
RUN cd /temp/dev && npm ci

RUN mkdir -p /temp/prod
COPY package.json package-lock.json /temp/prod/
COPY packages/common/package.json /temp/prod/packages/common/
COPY packages/server/package.json /temp/prod/packages/server/
RUN cd /temp/prod && npm ci --production && \
    cp -a /temp/prod/packages/server/node_modules/* /temp/prod/node_modules && rm -rf /temp/prod/packages/server/node_modules

FROM base AS build
COPY --from=install /temp/dev ./
COPY . .

ENV NODE_ENV="production"
RUN npm run build:client && npm run build:storybook && npm run build:server

FROM base AS release

ENV DEBUG="" NODE_ENV="production" PORT=80 HUSKY="0"

RUN apt-get update \
 && apt-get install -y ca-certificates \
 && echo "deb https://deb.debian.org/debian sid main non-free non-free-firmware" > /etc/apt/sources.list \
 && apt-get update \
 && apt-get install -y 7zip 7zip-rar tini openssl \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

COPY --from=install /temp/prod/node_modules ./node_modules
COPY --from=install /temp/prod/packages/server/package.json ./
COPY --from=build /bookReader/packages/server/dist/index.js ./
COPY --from=build /bookReader/packages/server/prisma prisma
COPY --from=build /bookReader/packages/server/scripts scripts
COPY --from=build /bookReader/packages/client/dist public

COPY docker-entrypoint.sh ./
RUN chmod +x docker-entrypoint.sh

# "/bookReader/production.sqlite" is file
VOLUME ["/bookReader/storage"]

ENTRYPOINT ["tini", "--", "/bookReader/docker-entrypoint.sh"]
