mutation edit($id: ID! $name: String $thumbnail: String $finished: Boolean $invisible: Boolean) {
    edit: editBookInfo(id: $id name: $name thumbnail: $thumbnail finished: $finished invisible: $invisible) {
        success
        code
    }
}
