query ($limit: Int! $offset: Int! $search: String $order: BookInfoOrder $history: Boolean $invisible: Boolean $normal: Boolean){
    bookInfos(limit: $limit offset: $offset search: $search order: $order history: $history invisible: $invisible normal: $normal) {
        length
        infos {
            id
            name
            count
            thumbnail
            history
            finished
            invisible
        }
    }
}
