query ($id: ID!){
    bookInfo(id: $id) {
        id
        name
        books {
            id
            number
            pages
            thumbnail

            info {
                id
            }
        }
    }
}
