name: Docker Image CI

# - '[0-9.]+*'
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: $(cat ${GITHUB_EVENT_PATH} | jq -r ".ref")
      - name: Build the Docker image
        run: |
          docker build . \
          --file Dockerfile \
          --tag docker.pkg.github.com/syuchan1005/bookreader/book_reader:$(cat ${GITHUB_EVENT_PATH} | jq -r ".ref" | grep -Po "([^/]+)$")
      - name: check images
        run: docker images
