name: Docker Image CI

on:
  push:
    tags:
#      - '[0-9.]+*'
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: git checkout $tag
        run: git checkout $(cat ${GITHUB_EVENT_PATH} | jq -r ".ref")
      - name: Build the Docker image
        run: |
          docker build . \
          --file Dockerfile \
          --tag docker.pkg.github.com/syuchan1005/bookreader/book_reader:$(cat ${GITHUB_EVENT_PATH} | jq -r ".ref" | grep -Po "([^/]+)$")
      - name: check images
        run: docker images
      - name: Deploy github-package-registry (docker)
        run: |
          docker login docker.pkg.github.com -u "${{ secrets.GITHUB_USERNAME }}" -p "${{ secrets.GITHUB_TOKEN }}" \
          && docker push docker.pkg.github.com/syuchan1005/bookreader/book_reader:$(cat ${GITHUB_EVENT_PATH} | jq -r ".ref" | grep -Po "([^/]+)$")
