name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: commit
        run: cat ${GITHUB_EVENT_PATH} | jq -r ".after"
      - name: tag
        run: cat ${GITHUB_EVENT_PATH} | jq -r ".ref" | grep -Po "([^/]+)$"
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag docker.pkg.github.com/syuchan1005/bookreader/BookReader:${cat ${GITHUB_EVENT_PATH} | jq -r '.commits[0]'}
